### ISSUE TITLE
Issues with Rancher/Docker and containers

### ISSUE THREAD

**Issue by jnylen** [elbow-jason/durango#4]
Hi @elbow-jason,
I have an issue where its complaining it can't reach the hostname of "arangodb" even though I can ping it fine:
```
2018-08-09 14:16:5312:16:53.539 [info] OpenExchangeRates Updating Rates...
2018-08-09 14:16:5312:16:53.548 [info] Running ServerWeb.Endpoint with Cowboy using http://0.0.0.0:4000
2018-08-09 14:16:5312:16:53.565 [info] Application server exited: Server.Application.start(:normal, [:durango]) returned an error: shutdown: failed to start child: Server.Repo
2018-08-09 14:16:53    ** (EXIT) an exception was raised:
2018-08-09 14:16:53        ** (RuntimeError) Invalid Durango.Repo.Auth response :nxdomain for Elixir.Server.Repo
2018-08-09 14:16:53            (durango) lib/repo/auth.ex:24: Durango.Repo.Auth.refresh_token/1
2018-08-09 14:16:53            (server) lib/server/repo.ex:2: Server.Repo.refresh_token/1
2018-08-09 14:16:53            (server) lib/server/repo.ex:2: Server.Repo.init/1
2018-08-09 14:16:53            (stdlib) gen_server.erl:374: :gen_server.init_it/2
2018-08-09 14:16:53            (stdlib) gen_server.erl:342: :gen_server.init_it/6
2018-08-09 14:16:53            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
2018-08-09 14:16:55{"Kernel pid terminated",application_controller,"{application_start_failure,server,{{shutdown,{failed_to_start_child,'Elixir.Server.Repo',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<\"Invalid Durango.Repo.Auth response :nxdomain for Elixir.Server.Repo\">>},[{'Elixir.Durango.Repo.Auth',refresh_token,1,[{file,\"lib/repo/auth.ex\"},{line,24}]},{'Elixir.Server.Repo',refresh_token,1,[{file,\"lib/server/repo.ex\"},{line,2}]},{'Elixir.Server.Repo',init,1,[{file,\"lib/server/repo.ex\"},{line,2}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.Server.Application',start,[normal,[durango]]}}}"}
2018-08-09 14:16:55Kernel pid terminated (application_controller) ({application_start_failure,server,{{shutdown,{failed_to_start_child,'Elixir.Server.Repo',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError
2018-08-09 14:16:55
2018-08-09 14:16:55Crash dump is being written to: erl_crash.dump...done
```

Any ideas?

**Comment by jnylen** [comment]
NVM,
Fixed.
